import React, { createContext, useContext, useState, useEffect, useRef } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { lightColors, darkColors } from '../theme';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'bn' | 'mr';

const DARK_KEY = 'flyeasy_dark_mode';
const LANG_KEY = 'flyeasy_language';

// ─── Translations ────────────────────────────────────────────────────────────
export const translations = {
  en: {
    appTagline: 'Fly Without the Fear',
    quickActions: 'Quick Actions',
    leaveByTitle: 'Leave-By',
    leaveByDesc: 'When should I leave home?',
    docCheckTitle: 'Checklist',
    docCheckDesc: 'Am I ready to fly?',
    flightAlertsTitle: 'Alerts',
    flightAlertsDesc: 'Gate changes & delays',
    calmModeTitle: 'Calm Mode',
    calmModeDesc: 'Relax & breathe',
    // Menu
    settingsTitle: 'Settings',
    darkMode: 'Dark Mode',
    language: 'Language',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    upgradePremium: 'Upgrade to Premium 👑',
    appVersion: 'FlyEasy v1.0.0',
    close: 'Close',
    // Flight status
    statusOnTime: 'On Time',
    statusDelayed: 'Delayed',
    statusCancelled: 'Cancelled',
    statusLanded: 'Landed',
    statusDiverted: 'Diverted',
    statusScheduled: 'Scheduled',
    statusActive: 'In Air',
    statusBoardingNow: 'Boarding',
    statusDeparted: 'Departed',
    // Common actions
    comingSoon: 'Coming Soon',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    refresh: 'Refresh',
    search: 'Search',
    addFlight: 'Add Flight',
    noFlights: 'No flights yet',
    back: 'Back',
    done: 'Done',
    loading: 'Loading…',
    tryAgain: 'Try Again',
    // Errors
    errorGeneric: 'Something went wrong. Please try again.',
    errorNoInternet: 'No internet connection.',
    errorFlightNotFound: 'Flight not found. Check number & date.',
    errorApiLimit: 'Too many requests. Please wait a moment.',
    // Leave-By
    leaveByHeading: 'Leave-By Calculator',
    leaveBySubheading: 'Know exactly when to leave home',
    leaveByMissingTime: 'Please enter a valid departure time (e.g. 10:30 AM).',
    leaveByMissingTravel: 'Please enter your travel time to the airport in minutes.',
    leaveByResultLabel: 'Leave home by',
    leaveByReminderSet: '🔔 Reminder set for 15 min before',
    // Doc checklist
    checklistHeading: 'Document Checklist',
    checklistDomestic: '🇮🇳 Domestic',
    checklistIntl: '🌍 International',
    checklistShare: '📤 Share Checklist',
    checklistReset: '🔄 Reset',
    checklistAllDone: '  ✅ All done!',
    // Premium
    premiumTitle: 'FlyEasy Premium',
    premiumSubtitle: 'Fly smarter. Worry less.',
    premiumCta: 'Upgrade to Premium',
    premiumAlreadyActive: 'You\'re Premium!',
    // Number formatting — Indian system
    numberFormat: 'en-IN',
  },
  hi: {
    appTagline: 'डर के बिना उड़ान',
    quickActions: 'त्वरित क्रियाएं',
    leaveByTitle: 'प्रस्थान',
    leaveByDesc: 'घर से कब निकलूं?',
    docCheckTitle: 'जाँच सूची',
    docCheckDesc: 'क्या मैं तैयार हूं?',
    flightAlertsTitle: 'अलर्ट',
    flightAlertsDesc: 'गेट बदलाव और देरी',
    calmModeTitle: 'शांत मोड',
    calmModeDesc: 'आराम करें, सांस लें',
    // Menu
    settingsTitle: 'सेटिंग्स',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    upgradePremium: 'प्रीमियम अपग्रेड करें 👑',
    appVersion: 'FlyEasy v1.0.0',
    close: 'बंद करें',
    // Flight status
    statusOnTime: 'समय पर',
    statusDelayed: 'विलंबित',
    statusCancelled: 'रद्द',
    statusLanded: 'उतर चुकी',
    statusDiverted: 'मार्ग बदला',
    statusScheduled: 'निर्धारित',
    statusActive: 'हवा में',
    statusBoardingNow: 'बोर्डिंग',
    statusDeparted: 'उड़ चुकी',
    // Common actions
    comingSoon: 'जल्द आ रहा है',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    refresh: 'रिफ्रेश',
    search: 'खोजें',
    addFlight: 'उड़ान जोड़ें',
    noFlights: 'कोई उड़ान नहीं',
    back: 'वापस',
    done: 'हो गया',
    loading: 'लोड हो रहा है…',
    tryAgain: 'पुनः प्रयास करें',
    // Errors
    errorGeneric: 'कुछ गलत हुआ। कृपया पुनः प्रयास करें।',
    errorNoInternet: 'इंटरनेट कनेक्शन नहीं है।',
    errorFlightNotFound: 'उड़ान नहीं मिली। नंबर और तारीख जांचें।',
    errorApiLimit: 'बहुत अधिक अनुरोध। थोड़ा इंतज़ार करें।',
    // Leave-By
    leaveByHeading: 'प्रस्थान समय कैलकुलेटर',
    leaveBySubheading: 'जानें घर से कब निकलना है',
    leaveByMissingTime: 'कृपया सही प्रस्थान समय दर्ज करें (जैसे 10:30 AM)।',
    leaveByMissingTravel: 'कृपया हवाई अड्डे तक यात्रा का समय मिनटों में दर्ज करें।',
    leaveByResultLabel: 'घर से निकलें',
    leaveByReminderSet: '🔔 15 मिनट पहले रिमाइंडर सेट हुआ',
    // Doc checklist
    checklistHeading: 'दस्तावेज़ जाँच सूची',
    checklistDomestic: '🇮🇳 घरेलू',
    checklistIntl: '🌍 अंतर्राष्ट्रीय',
    checklistShare: '📤 साझा करें',
    checklistReset: '🔄 रीसेट',
    checklistAllDone: '  ✅ सब तैयार!',
    // Premium
    premiumTitle: 'FlyEasy प्रीमियम',
    premiumSubtitle: 'और स्मार्ट उड़ान भरें।',
    premiumCta: 'प्रीमियम अपग्रेड करें',
    premiumAlreadyActive: 'आप प्रीमियम हैं!',
    // Number formatting — Indian system
    numberFormat: 'hi-IN',
  },

  // ─── Tamil ──────────────────────────────────────────────────────────────────
  ta: {
    appTagline: 'பயமில்லாமல் பறக்கவும்',
    quickActions: 'விரைவு செயல்கள்',
    leaveByTitle: 'புறப்படு',
    leaveByDesc: 'வீட்டிலிருந்து எப்போது கிளம்பு?',
    docCheckTitle: 'சரிபார்ப்பு',
    docCheckDesc: 'நான் பறக்க தயாரா?',
    flightAlertsTitle: 'விழிப்பூட்டல்',
    flightAlertsDesc: 'வாயில் மாற்றங்கள் & தாமதங்கள்',
    calmModeTitle: 'அமைதி மோட்',
    calmModeDesc: 'ஓய்வெடு, சுவாசி',
    settingsTitle: 'அமைப்புகள்',
    darkMode: 'இருண்ட பயன்முறை',
    language: 'மொழி',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    upgradePremium: 'பிரீமியத்திற்கு மேம்படுத்து 👑',
    appVersion: 'FlyEasy v1.0.0',
    close: 'மூடு',
    statusOnTime: 'சரியான நேரம்',
    statusDelayed: 'தாமதம்',
    statusCancelled: 'ரத்து',
    statusLanded: 'தரையிறங்கியது',
    statusDiverted: 'திசைதிருப்பப்பட்டது',
    statusScheduled: 'திட்டமிடப்பட்டது',
    statusActive: 'வானில்',
    statusBoardingNow: 'ஏறுகிறோம்',
    statusDeparted: 'புறப்பட்டது',
    comingSoon: 'விரைவில் வருகிறது',
    save: 'சேமி',
    cancel: 'ரத்துசெய்',
    delete: 'நீக்கு',
    refresh: 'புதுப்பி',
    search: 'தேடு',
    addFlight: 'விமானம் சேர்',
    noFlights: 'விமானங்கள் இல்லை',
    back: 'பின்செல்',
    done: 'முடிந்தது',
    loading: 'ஏற்றுகிறது…',
    tryAgain: 'மீண்டும் முயற்சி',
    errorGeneric: 'ஏதோ தவறாகிவிட்டது. மீண்டும் முயற்சிக்கவும்.',
    errorNoInternet: 'இணைய இணைப்பு இல்லை.',
    errorFlightNotFound: 'விமானம் கிடைக்கவில்லை. எண் & தேதி சரிபார்க்கவும்.',
    errorApiLimit: 'அதிக கோரிக்கைகள். சிறிது காத்திருக்கவும்.',
    leaveByHeading: 'புறப்பாட்டு நேர கணக்கீடு',
    leaveBySubheading: 'எப்போது கிளம்பவேண்டும் என்று அறிக',
    leaveByMissingTime: 'சரியான புறப்பாட்டு நேரம் உள்ளிடவும்.',
    leaveByMissingTravel: 'விமான நிலையத்திற்கு பயண நேரம் நிமிடங்களில் உள்ளிடவும்.',
    leaveByResultLabel: 'வீட்டிலிருந்து கிளம்பு',
    leaveByReminderSet: '🔔 15 நிமிடங்கள் முன் நினைவூட்டல் அமைக்கப்பட்டது',
    checklistHeading: 'ஆவண சரிபார்ப்பு பட்டியல்',
    checklistDomestic: '🇮🇳 உள்நாட்டு',
    checklistIntl: '🌍 சர்வதேசம்',
    checklistShare: '📤 பகிர்',
    checklistReset: '🔄 மீட்டமை',
    checklistAllDone: '  ✅ அனைத்தும் தயார்!',
    premiumTitle: 'FlyEasy பிரீமியம்',
    premiumSubtitle: 'புத்திசாலியாக பறக்கவும்.',
    premiumCta: 'பிரீமியத்திற்கு மேம்படுத்து',
    premiumAlreadyActive: 'நீங்கள் பிரீமியம்!',
    numberFormat: 'ta-IN',
  },

  // ─── Telugu ─────────────────────────────────────────────────────────────────
  te: {
    appTagline: 'భయం లేకుండా ఎగరండి',
    quickActions: 'శీఘ్ర చర్యలు',
    leaveByTitle: 'బయలుదేరు',
    leaveByDesc: 'ఇంటి నుండి ఎప్పుడు బయలుదేరాలి?',
    docCheckTitle: 'తనిఖీ',
    docCheckDesc: 'నేను ఎగరడానికి సిద్ధంగా ఉన్నానా?',
    flightAlertsTitle: 'హెచ్చరికలు',
    flightAlertsDesc: 'గేట్ మార్పులు & జాప్యాలు',
    calmModeTitle: 'ప్రశాంత మోడ్',
    calmModeDesc: 'విశ్రాంతి తీసుకోండి, శ్వాసించండి',
    settingsTitle: 'సెట్టింగ్‌లు',
    darkMode: 'డార్క్ మోడ్',
    language: 'భాష',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    upgradePremium: 'ప్రీమియంకు అప్‌గ్రేడ్ 👑',
    appVersion: 'FlyEasy v1.0.0',
    close: 'మూసివేయి',
    statusOnTime: 'సమయానికి',
    statusDelayed: 'ఆలస్యం',
    statusCancelled: 'రద్దు',
    statusLanded: 'దిగింది',
    statusDiverted: 'దారి మళ్ళింది',
    statusScheduled: 'షెడ్యూల్ చేయబడింది',
    statusActive: 'గాలిలో',
    statusBoardingNow: 'బోర్డింగ్',
    statusDeparted: 'బయలుదేరింది',
    comingSoon: 'త్వరలో వస్తుంది',
    save: 'సేవ్',
    cancel: 'రద్దు',
    delete: 'తొలగించు',
    refresh: 'రిఫ్రెష్',
    search: 'వెతకు',
    addFlight: 'విమానం జోడించు',
    noFlights: 'విమానాలు లేవు',
    back: 'వెనక్కి',
    done: 'పూర్తయింది',
    loading: 'లోడ్ అవుతోంది…',
    tryAgain: 'మళ్ళీ ప్రయత్నించు',
    errorGeneric: 'ఏదో తప్పు జరిగింది. మళ్ళీ ప్రయత్నించండి.',
    errorNoInternet: 'ఇంటర్నెట్ కనెక్షన్ లేదు.',
    errorFlightNotFound: 'విమానం కనుగొనబడలేదు. నంబర్ & తేదీ తనిఖీ చేయండి.',
    errorApiLimit: 'చాలా అభ్యర్థనలు. కొంత సేపు వేచి ఉండండి.',
    leaveByHeading: 'బయలుదేరే సమయ కాలిక్యులేటర్',
    leaveBySubheading: 'ఇంటి నుండి ఎప్పుడు బయలుదేరాలో తెలుసుకోండి',
    leaveByMissingTime: 'దయచేసి సరైన నిష్క్రమణ సమయం నమోదు చేయండి.',
    leaveByMissingTravel: 'విమానాశ్రయానికి ప్రయాణ సమయం నిమిషాల్లో నమోదు చేయండి.',
    leaveByResultLabel: 'ఇంటి నుండి బయలుదేరండి',
    leaveByReminderSet: '🔔 15 నిమిషాల ముందు రిమైండర్ సెట్ చేయబడింది',
    checklistHeading: 'పత్రాల తనిఖీ జాబితా',
    checklistDomestic: '🇮🇳 దేశీయ',
    checklistIntl: '🌍 అంతర్జాతీయ',
    checklistShare: '📤 షేర్',
    checklistReset: '🔄 రీసెట్',
    checklistAllDone: '  ✅ అన్నీ సిద్ధం!',
    premiumTitle: 'FlyEasy ప్రీమియమ్',
    premiumSubtitle: 'తెలివిగా ఎగరండి.',
    premiumCta: 'ప్రీమియంకు అప్‌గ్రేడ్ చేయండి',
    premiumAlreadyActive: 'మీరు ప్రీమియమ్!',
    numberFormat: 'te-IN',
  },

  // ─── Kannada ────────────────────────────────────────────────────────────────
  kn: {
    appTagline: 'ಭಯವಿಲ್ಲದೆ ಹಾರಾಡಿ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    leaveByTitle: 'ಹೊರಡುವ ಸಮಯ',
    leaveByDesc: 'ಮನೆಯಿಂದ ಯಾವಾಗ ಹೊರಡಬೇಕು?',
    docCheckTitle: 'ಪರಿಶೀಲನೆ',
    docCheckDesc: 'ನಾನು ಹಾರಲು ಸಿದ್ಧನೇ?',
    flightAlertsTitle: 'ಎಚ್ಚರಿಕೆ',
    flightAlertsDesc: 'ಗೇಟ್ ಬದಲಾವಣೆ & ವಿಳಂಬ',
    calmModeTitle: 'ಶಾಂತ ಮೋಡ್',
    calmModeDesc: 'ವಿಶ್ರಮಿಸಿ, ಉಸಿರಾಡಿ',
    settingsTitle: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    language: 'ಭಾಷೆ',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
    upgradePremium: 'ಪ್ರೀಮಿಯಂಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ 👑',
    appVersion: 'FlyEasy v1.0.0',
    close: 'ಮುಚ್ಚು',
    statusOnTime: 'ಸಮಯಕ್ಕೆ',
    statusDelayed: 'ತಡವಾಗಿದೆ',
    statusCancelled: 'ರದ್ದುಗೊಂಡಿದೆ',
    statusLanded: 'ಇಳಿದಿದೆ',
    statusDiverted: 'ಬೇರೆ ದಾರಿ',
    statusScheduled: 'ನಿಗದಿತ',
    statusActive: 'ಆಕಾಶದಲ್ಲಿ',
    statusBoardingNow: 'ಹತ್ತುವಿಕೆ',
    statusDeparted: 'ಹೊರಟಿದೆ',
    comingSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತದೆ',
    save: 'ಉಳಿಸು',
    cancel: 'ರದ್ದು',
    delete: 'ಅಳಿಸು',
    refresh: 'ರಿಫ್ರೆಶ್',
    search: 'ಹುಡುಕಿ',
    addFlight: 'ವಿಮಾನ ಸೇರಿಸಿ',
    noFlights: 'ವಿಮಾನಗಳಿಲ್ಲ',
    back: 'ಹಿಂದೆ',
    done: 'ಮುಗಿದಿದೆ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    errorGeneric: 'ಏನೋ ತಪ್ಪಾಯಿತು. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    errorNoInternet: 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ.',
    errorFlightNotFound: 'ವಿಮಾನ ಕಂಡುಬಂದಿಲ್ಲ. ಸಂಖ್ಯೆ & ದಿನಾಂಕ ಪರಿಶೀಲಿಸಿ.',
    errorApiLimit: 'ಹೆಚ್ಚಿನ ವಿನಂತಿಗಳು. ಸ್ವಲ್ಪ ಕಾಯಿರಿ.',
    leaveByHeading: 'ಹೊರಡುವ ಸಮಯ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    leaveBySubheading: 'ಮನೆಯಿಂದ ಯಾವಾಗ ಹೊರಡಬೇಕೆಂದು ತಿಳಿಯಿರಿ',
    leaveByMissingTime: 'ದಯವಿಟ್ಟು ಸರಿಯಾದ ನಿರ್ಗಮನ ಸಮಯ ನಮೂದಿಸಿ.',
    leaveByMissingTravel: 'ವಿಮಾನ ನಿಲ್ದಾಣಕ್ಕೆ ಪ್ರಯಾಣದ ಸಮಯ ನಿಮಿಷಗಳಲ್ಲಿ ನಮೂದಿಸಿ.',
    leaveByResultLabel: 'ಮನೆಯಿಂದ ಹೊರಡಿ',
    leaveByReminderSet: '🔔 15 ನಿಮಿಷಗಳ ಮೊದಲು ರಿಮೈಂಡರ್ ಹೊಂದಿಸಲಾಗಿದೆ',
    checklistHeading: 'ದಾಖಲೆ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ',
    checklistDomestic: '🇮🇳 ದೇಶೀಯ',
    checklistIntl: '🌍 ಅಂತರಾಷ್ಟ್ರೀಯ',
    checklistShare: '📤 ಹಂಚಿಕೊಳ್ಳಿ',
    checklistReset: '🔄 ರೀಸೆಟ್',
    checklistAllDone: '  ✅ ಎಲ್ಲಾ ಸಿದ್ಧ!',
    premiumTitle: 'FlyEasy ಪ್ರೀಮಿಯಂ',
    premiumSubtitle: 'ಚಾಣಾಕ್ಷತೆಯಿಂದ ಹಾರಿ.',
    premiumCta: 'ಪ್ರೀಮಿಯಂಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ',
    premiumAlreadyActive: 'ನೀವು ಪ್ರೀಮಿಯಂ!',
    numberFormat: 'kn-IN',
  },

  // ─── Bengali ────────────────────────────────────────────────────────────────
  bn: {
    appTagline: 'ভয় ছাড়া উড়ুন',
    quickActions: 'দ্রুত ক্রিয়া',
    leaveByTitle: 'যাত্রার সময়',
    leaveByDesc: 'বাড়ি থেকে কখন যাব?',
    docCheckTitle: 'চেকলিস্ট',
    docCheckDesc: 'আমি উড়তে প্রস্তুত?',
    flightAlertsTitle: 'সতর্কতা',
    flightAlertsDesc: 'গেট পরিবর্তন ও বিলম্ব',
    calmModeTitle: 'শান্ত মোড',
    calmModeDesc: 'বিশ্রাম নিন, শ্বাস নিন',
    settingsTitle: 'সেটিংস',
    darkMode: 'ডার্ক মোড',
    language: 'ভাষা',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsOfService: 'পরিষেবার শর্তাবলী',
    upgradePremium: 'প্রিমিয়ামে আপগ্রেড করুন 👑',
    appVersion: 'FlyEasy v1.0.0',
    close: 'বন্ধ',
    statusOnTime: 'সময়মতো',
    statusDelayed: 'বিলম্বিত',
    statusCancelled: 'বাতিল',
    statusLanded: 'অবতরণ',
    statusDiverted: 'পথ পরিবর্তন',
    statusScheduled: 'নির্ধারিত',
    statusActive: 'আকাশে',
    statusBoardingNow: 'বোর্ডিং',
    statusDeparted: 'যাত্রা করেছে',
    comingSoon: 'শীঘ্রই আসছে',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    refresh: 'রিফ্রেশ',
    search: 'খুঁজুন',
    addFlight: 'ফ্লাইট যোগ করুন',
    noFlights: 'কোনো ফ্লাইট নেই',
    back: 'পিছনে',
    done: 'সম্পন্ন',
    loading: 'লোড হচ্ছে…',
    tryAgain: 'আবার চেষ্টা করুন',
    errorGeneric: 'কিছু ভুল হয়েছে। আবার চেষ্টা করুন।',
    errorNoInternet: 'ইন্টারনেট সংযোগ নেই।',
    errorFlightNotFound: 'ফ্লাইট পাওয়া যায়নি। নম্বর ও তারিখ যাচাই করুন।',
    errorApiLimit: 'অনেক অনুরোধ। একটু অপেক্ষা করুন।',
    leaveByHeading: 'যাত্রার সময় ক্যালকুলেটর',
    leaveBySubheading: 'বাড়ি থেকে কখন বের হবেন তা জানুন',
    leaveByMissingTime: 'দয়া করে সঠিক প্রস্থান সময় লিখুন।',
    leaveByMissingTravel: 'বিমানবন্দরে যাত্রার সময় মিনিটে লিখুন।',
    leaveByResultLabel: 'বাড়ি থেকে বের হন',
    leaveByReminderSet: '🔔 ১৫ মিনিট আগে রিমাইন্ডার সেট হয়েছে',
    checklistHeading: 'নথি চেকলিস্ট',
    checklistDomestic: '🇮🇳 অভ্যন্তরীণ',
    checklistIntl: '🌍 আন্তর্জাতিক',
    checklistShare: '📤 শেয়ার',
    checklistReset: '🔄 রিসেট',
    checklistAllDone: '  ✅ সব প্রস্তুত!',
    premiumTitle: 'FlyEasy প্রিমিয়াম',
    premiumSubtitle: 'আরও স্মার্টভাবে উড়ুন।',
    premiumCta: 'প্রিমিয়ামে আপগ্রেড করুন',
    premiumAlreadyActive: 'আপনি প্রিমিয়াম!',
    numberFormat: 'bn-IN',
  },

  // ─── Marathi ────────────────────────────────────────────────────────────────
  mr: {
    appTagline: 'भीतीशिवाय उड़ा',
    quickActions: 'जलद क्रिया',
    leaveByTitle: 'निघण्याची वेळ',
    leaveByDesc: 'घरून कधी निघायचे?',
    docCheckTitle: 'तपासणी',
    docCheckDesc: 'मी उड्डाणासाठी तयार आहे का?',
    flightAlertsTitle: 'सूचना',
    flightAlertsDesc: 'गेट बदल आणि विलंब',
    calmModeTitle: 'शांत मोड',
    calmModeDesc: 'विश्रांती घ्या, श्वास घ्या',
    settingsTitle: 'सेटिंग्ज',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    privacyPolicy: 'गोपनीयता धोरण',
    termsOfService: 'सेवा अटी',
    upgradePremium: 'प्रीमियमवर अपग्रेड करा 👑',
    appVersion: 'FlyEasy v1.0.0',
    close: 'बंद करा',
    statusOnTime: 'वेळेवर',
    statusDelayed: 'उशीर',
    statusCancelled: 'रद्द',
    statusLanded: 'उतरले',
    statusDiverted: 'मार्ग बदलला',
    statusScheduled: 'निर्धारित',
    statusActive: 'हवेत',
    statusBoardingNow: 'बोर्डिंग',
    statusDeparted: 'निघाले',
    comingSoon: 'लवकरच येत आहे',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    refresh: 'रिफ्रेश',
    search: 'शोधा',
    addFlight: 'उड्डाण जोडा',
    noFlights: 'कोणतेही उड्डाण नाही',
    back: 'मागे',
    done: 'झाले',
    loading: 'लोड होत आहे…',
    tryAgain: 'पुन्हा प्रयत्न करा',
    errorGeneric: 'काहीतरी चुकले. पुन्हा प्रयत्न करा.',
    errorNoInternet: 'इंटरनेट जोडणी नाही.',
    errorFlightNotFound: 'उड्डाण सापडले नाही. क्रमांक व तारीख तपासा.',
    errorApiLimit: 'जास्त विनंत्या. थोडा वेळ थांबा.',
    leaveByHeading: 'निघण्याच्या वेळेची गणना',
    leaveBySubheading: 'घरून नक्की कधी निघायचे ते जाणा',
    leaveByMissingTime: 'कृपया वैध प्रस्थान वेळ प्रविष्ट करा.',
    leaveByMissingTravel: 'विमानतळापर्यंत प्रवास वेळ मिनिटांमध्ये प्रविष्ट करा.',
    leaveByResultLabel: 'घरून निघा',
    leaveByReminderSet: '🔔 १५ मिनिटे आधी स्मरणपत्र सेट केले',
    checklistHeading: 'कागदपत्र तपासणी यादी',
    checklistDomestic: '🇮🇳 देशांतर्गत',
    checklistIntl: '🌍 आंतरराष्ट्रीय',
    checklistShare: '📤 शेअर करा',
    checklistReset: '🔄 रीसेट',
    checklistAllDone: '  ✅ सर्व तयार!',
    premiumTitle: 'FlyEasy प्रीमियम',
    premiumSubtitle: 'हुशारीने उड़ा.',
    premiumCta: 'प्रीमियमवर अपग्रेड करा',
    premiumAlreadyActive: 'तुम्ही प्रीमियम आहात!',
    numberFormat: 'mr-IN',
  },
};

// ─── Context type ─────────────────────────────────────────────────────────────
type SettingsContextType = {
  isDarkMode: boolean;
  toggleDarkMode: () => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
  themeColors: typeof lightColors;
};

const SettingsContext = createContext<SettingsContextType>({
  isDarkMode: false,
  toggleDarkMode: () => {},
  language: 'en',
  setLanguage: () => {},
  t: translations.en,
  themeColors: lightColors,
});

// ─── Provider ─────────────────────────────────────────────────────────────────
export function SettingsProvider({ children }: { children: React.ReactNode }) {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [language, setLanguageState] = useState<Language>('en');
  const initialised = useRef(false);

  // Load persisted settings on mount
  useEffect(() => {
    AsyncStorage.multiGet([DARK_KEY, LANG_KEY])
      .then((results: readonly [string, string | null][]) => {
        const darkVal = results[0][1];
        const langVal = results[1][1];
        if (darkVal !== null) { setIsDarkMode(darkVal === 'true'); }
        const validLangs: Language[] = ['en', 'hi', 'ta', 'te', 'kn', 'bn', 'mr'];
        if (langVal && validLangs.includes(langVal as Language)) {
          setLanguageState(langVal as Language);
        }
      })
      .finally(() => {
        initialised.current = true;
      });
  }, []);

  const toggleDarkMode = () => {
    setIsDarkMode(prev => {
      const next = !prev;
      AsyncStorage.setItem(DARK_KEY, String(next)).catch(() => {});
      return next;
    });
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    AsyncStorage.setItem(LANG_KEY, lang).catch(() => {});
  };

  const value: SettingsContextType = {
    isDarkMode,
    toggleDarkMode,
    language,
    setLanguage,
    t: translations[language],
    themeColors: isDarkMode ? darkColors : lightColors,
  };

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export const useSettings = () => useContext(SettingsContext);
